const express = require('express')
const cors = require('cors')
const { taskQueue } = require('../lib/task-queue')

const app = express()
const PORT = process.env.PORT || 3001

// Middleware
app.use(cors())
app.use(express.json())

// Health check
app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    service: 'Agent Factory API',
    version: '1.0.0'
  })
})

// Task queue endpoints
app.get('/api/tasks', (req, res) => {
  try {
    const stats = taskQueue.getQueueStats()
    res.json({
      success: true,
      data: stats,
      timestamp: new Date().toISOString()
    })
  } catch (error) {
    console.error('Error getting queue stats:', error)
    res.status(500).json({
      success: false,
      error: 'Failed to get queue stats'
    })
  }
})

app.post('/api/tasks', (req, res) => {
  try {
    const task = req.body
    
    // Validate required fields
    if (!task.title) {
      return res.status(400).json({
        success: false,
        error: 'Task title is required'
      })
    }

    // Enqueue task
    const taskId = taskQueue.enqueueTask({
      id: '', // Will be generated by queue
      title: task.title,
      description: task.description || '',
      category: task.category || 'general',
      priority: task.priority || 'medium',
      estimatedComplexity: task.estimatedComplexity || 5,
      status: 'pending',
      createdAt: new Date()
    }, {
      priority: task.priority === 'critical' ? 5 : 
                task.priority === 'high' ? 4 :
                task.priority === 'medium' ? 3 : 2,
      maxRetries: task.maxRetries,
      timeoutMs: task.timeoutMs
    })

    res.json({
      success: true,
      data: { taskId },
      message: `Task "${task.title}" enqueued successfully`
    })
  } catch (error) {
    console.error('Error enqueuing task:', error)
    res.status(500).json({
      success: false,
      error: 'Failed to enqueue task'
    })
  }
})

// Agent endpoints
app.get('/api/agents', (req, res) => {
  // Mock agent data
  const agents = [
    {
      id: 'orchestrator',
      name: 'Orchestrator',
      description: 'Top-level agent coordinator',
      model: 'deepseek-v3.2',
      status: 'active',
      capabilities: ['task_classification', 'agent_delegation', 'result_synthesis']
    },
    {
      id: 'coder',
      name: 'Coder',
      description: 'Senior developer agent',
      model: 'deepseek-v3.2',
      status: 'active',
      capabilities: ['nextjs_development', 'github_pr_management', 'bug_fixes']
    },
    {
      id: 'marketing',
      name: 'Marketing',
      description: 'Marketing content agent',
      model: 'gemini-2.5-flash-lite',
      status: 'active',
      capabilities: ['content_generation', 'seo_optimization', 'campaign_management']
    }
  ]

  res.json({
    success: true,
    data: agents,
    count: agents.length
  })
})

// Start server
app.listen(PORT, () => {
  console.log(`Agent Factory API server running on http://localhost:${PORT}`)
  console.log(`Health check: http://localhost:${PORT}/health`)
  console.log(`Task queue: http://localhost:${PORT}/api/tasks`)
  console.log(`Agents list: http://localhost:${PORT}/api/agents`)
})