import { NextRequest, NextResponse } from 'next/server'
import { taskQueue } from '@/lib/task-queue'
import { Task } from '@/lib/delegation-engine'

export async function GET(request: NextRequest) {
  try {
    const stats = taskQueue.getQueueStats()
    return NextResponse.json({
      success: true,
      data: stats,
      timestamp: new Date().toISOString()
    })
  } catch (error) {
    console.error('Error getting queue stats:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to get queue stats' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    // Validate task
    const task: Task = {
      id: '', // Will be generated by queue
      title: body.title,
      description: body.description || '',
      category: body.category || 'general',
      priority: body.priority || 'medium',
      estimatedComplexity: body.estimatedComplexity || 5,
      status: 'pending',
      createdAt: new Date()
    }

    // Validate required fields
    if (!task.title) {
      return NextResponse.json(
        { success: false, error: 'Task title is required' },
        { status: 400 }
      )
    }

    // Enqueue task
    const taskId = await taskQueue.enqueueTask(task, {
      priority: body.priority === 'critical' ? 5 : 
                body.priority === 'high' ? 4 :
                body.priority === 'medium' ? 3 : 2,
      scheduledFor: body.scheduledFor ? new Date(body.scheduledFor) : undefined,
      maxRetries: body.maxRetries,
      timeoutMs: body.timeoutMs
    })

    return NextResponse.json({
      success: true,
      data: { taskId },
      message: `Task "${task.title}" enqueued successfully`
    })
  } catch (error) {
    console.error('Error enqueuing task:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to enqueue task' },
      { status: 500 }
    )
  }
}